language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g yarn
  - yarn global add codecov
  - yarn global add now
install:
  - yarn
script:
  - yarn test-ci
  - codecov
after_success:
  - ./.now/deploy.sh
